---
Name: mysite-nz-config
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

SilverStripe\View\SSViewer:
  themes:
    - $public
    - base
    - $default
SilverStripe\Control\Email\Email:
  admin_email: info@mysite.nz

SilverStripe\i18n\i18n:
  locale: en_NZ
  date_format: dd-MM-YYYY

SilverStripe\Admin\LeftAndMain:
  application_name: 'mysite.nz'

SilverStripe\Admin\ModelAdmin:
  page_length: 100

Sunnysideup\WebpackRequirementsBackend\Api\Configuration:
  webpack_theme: base
